### PR TITLE
Change loaded package name to avoid conflict

### PR DESCRIPTION
**Pull request by y0z**
## Motivation & Changes
Change loaded package name by adding optunahub_package post-fix to avoid module name confliction.

### CODE REVIEW

**Comment by y0z** [comment]
@HideakiImamura Could you review this PR?

**Comment by HideakiImamura** [comment]
I think this change is confusing for users because the imported module name is implicitly changed by optunahub.

**Comment by y0z** [comment]
I clarified this behavior in docstring.

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
